public with sharing class ClassToDel {
	
	public static void plsDonotDelMe(){
		
		for(integer i=0; i<=10; i++){
			
			system.debug('Warning Stay in your Limits');
			system.debug('Consequences won\'t be favaourable');
			system.debug('Lets see it comes or not');
			system.debug('Lets get a confict to see it works');
			system.debug('Wow it works');
			system.debug('User1 commits');
			system.debug('Conflict Win Round 1');
			system.debug('Round 2 starts');
		}
	}
    
}